# Site settings
title: Yvonne Beirne FitzGerald
description: 'Business Card Page'
url: 'http://thomas.zuehlke.family'
baseurl: ''
profilepic: '/images/YvonneH400x300.jpg'
bkimage: '/images/bk1.jpg'
#google_analytics: UA-XXXXXX-X
font_awesome: 'XXXXXXXXXX.js'

author:
  name: 'Yvonne Beirne FitzGerald'
  email: hi@theyvonne.com
  twitter_username: YvonFitz
#  facebook_username: joshgerdes
  github_username:  YvonneBeirneFitzGerald
  linkedin_username:  https://www.linkedin.com/in/yvonnefitzgerald/
 # meetup_name: Azure-Meetup-Rostock-MV

# Build settings
destination: _site
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

#plugins: ['jekyll-paginate']
exclude: ['README.md', 'screenshot-overview.png']
